### ISSUE TITLE
Access the activities etc. of the teams I'm administrating

### ISSUE THREAD

**Issue by forland** [Holdsport/holdsport-api#11]
Hi'

How come I can only access the activities of the teams im managing and not the ones I'm administrating??

Im connection to "https://api.holdsport.dk/v1/teams/" with my personal username and password - and I am holdsport administrator in our club. I would expect to be able to se the same data (activities etc.) on the API call as I can in Holdsport - the UI version

**Comment by Pings228** [comment]
I had the same issue. But I found out you need to be assoissated with every Team you want to have REST access to. Either as a trainer or as a clubadmin.

**Comment by AllanJP-DK** [comment]
Hi,
I'm in the same situation... I'm an administrator in the club, but i can only access the list of teams in the club, but not for example the members of the team... Except the teams I'm a coach at... Teams I can see for example members on are the teams that are returned with a role: 2 but all other teams have role: null .... Is it correct that club admins doesnt have access to for example team members?

All off course via the API

**Comment by joerichsen** [comment]
I have made an update that opens up access for club admins to activities and team members using the API :-)
