### ISSUE TITLE
user details doesn't include the two custom fields

### ISSUE THREAD

**Issue by Folkenberg** [Holdsport/holdsport-api#12]
When querying for members of a team (https://api.holdsport.dk/v1/teams/[TEAMID]/members) or simple the details of the current user (https://api.holdsport.dk/v1/user), the response doesn't include the two custom fields. In our example, the custom field was named 'Discord ID' and all access checkmarks was enabled. But no entry in the API response. 

These data fields are serialized to the excel export, so it seems like a bug that it doesn't get serialized to the API response.

**Comment by joerichsen** [comment]
Now the custom fields are part of the response when querying team members.

It looks like this

```
  "club_fields": [
            {
                "club_field_id": 1,
                "value": "ja"
            },
            {
                "club_field_id": 2,
                "value": ""
            }
        ],
````
