### ISSUE TITLE
missing role value when user is 'admin'

### ISSUE THREAD

**Issue by Folkenberg** [Holdsport/holdsport-api#13]
When requesting for list of teams, a 'admin' user will get a list of all teams administered.
However, the 'role' property will be *null* and the admin user will not have access to query further into the team for list of members etc.

In the documentation / README.md file, it is stated that "the role field can have five possible values 1 for player, 2 for coach, 3 for assistant coach, 4 for injured, and 5 for inactive."
- It clearly can also be *null* and hence make admin accounts useless in regards to API usage. 

Should be fixed.

**Comment by joerichsen** [comment]
Thank you for reporting this. I have opened up access for admins to the team members and team activities in https://github.com/Holdsport/holdsport-api/issues/11
