### ISSUE TITLE
Personal information of team members

### ISSUE THREAD

**Issue by daniel-mizsak** [Holdsport/holdsport-api#19]
I can see that based on the [Getting the list of team members](https://github.com/Holdsport/holdsport-api?tab=readme-ov-file#getting-the-list-of-team-members) part of the documentation this is the intended behavior, but is it really expected that without having any elavated privilages I can query a lot of personal information about my team members? Such as `phone number`, `e-mail address` or `phisical address`.

This seems especially concerning to me, as in the phone app I could not find this kind of information for others, and all of these fields are mandatory for registration.

**Comment by joerichsen** [comment]
Ah, good call. I have changed the system so that the user accessing the API now sees the same information as on the web and in the app. Thanks.

**Comment by daniel-mizsak** [comment]
I am glad I could help. 👍

For now I still get all the information, but I could image that it takes some time to implement all necessary permission checks.

Once fully updated I can help updating the `README.md` with the new expected values if needed.

**Comment by joerichsen** [comment]
You will still get all the fields but with empty values for the data that you don't have permission to see.

Note that this also means that you will be able to see your own address (because you are allowed to see your own address).

The data should reflect what you see, if you log in to the web version with the same username as you use to query the API.

If not, please get in touch and I will have another look 👍 (Comment here or send an email to joergen @ hold...)

**Comment by daniel-mizsak** [comment]
Well, on the website https://www.holdsport.dk/members I can confirm that I see columns like `address` or `mobile` and it does not show any value. (I can only see `role` and `gender` values.)

But when I make queries either with `curl` or with my python script, the values are still showing up. My request script:

```python
import json

import requests
from dotenv import dotenv_values

if __name__ == "__main__":
    config = dotenv_values(".env")

    team_id = config["TEAM_ID"]
    auth = (config["HOLDSPORT_USERNAME"], config["HOLDSPORT_PASSWORD"])

    team_members = requests.get(f"https://api.holdsport.dk/v1/teams/{team_id}/members", auth=auth, timeout=5)

    print(json.dumps(team_members.json(), indent=2))
```
<br>

I can send you further information in e-mail if you need anything. 👍

**Comment by joerichsen** [comment]
If you email me the value of HOLDSPORT_USERNAME that you use, I can have a look 👍

**Comment by joerichsen** [comment]
With some debugging support from @daniel-mizsak we have sorted out this issue now :-)
