### ISSUE TITLE
Error code 500 when trying to manipulate user status 

### ISSUE THREAD

**Issue by jeyben** [Holdsport/holdsport-api#2]
I try to manipulate an activity by posting new status for an activity. The server returns a errorcode 500 and returns a HTML document when calling this:

curl -H "Content-Type: application/json" -X POST -u “<username>:<password>” https://api.holdsport.dk/v1/activities/3465227/activities_users -d '{“activities_user":{"picked":1,"joined_status":1}}'

I know the credentials I use is correct as the server returns a 401 in case of bad credentials.

I will not write my credentials here, but If you need help reproducing this, let me know

**Comment by joerichsen** [comment]
I just checked the error logging system and it had the following error:

```
MultiJson::ParseError: 795: unexpected token at '{???activities_user":{"picked":1,"joined_status":1}}'
```

and when I look at your example it seems to have a weird quote at that place

```
-d '{“activities_user"
```

(the first double quote is kind of strange :-)

**Comment by jeyben** [comment]
Thank for you feedback! My original issues was a missing content-type header, and when I tried to create a curl example this little typo (copy/paste from a a formatted text document) was introduced which didn't make it easier :-( But now it works! - also using curl :-)
