### ISSUE TITLE
Adding activities_coaches to all activities?

### ISSUE THREAD

**Issue by jeyben** [Holdsport/holdsport-api#3]
Currently there is no way to detect how many coaches are attending a given activity as the "activities_coaches" isn't available to all activities.

Could that number array be added? along with the same properties as an activity user?
{
        "id": 2363898, 
        "name": "Demo Demo", 
        "status": "tilmeldt", 
        "updated_at": "2011-12-21T14:03:42+01:00", 
        "user_id": 58856
    }

or coaches could be added to the list of activity_users together with the role property (making ti possible to see the difference between coaches and ordinary users)

**Comment by joerichsen** [comment]
I could add a coach_count field to the json for an activity. Would that work for you?

Ie. something like

```
{
    "comment": "", 
    "endtime": "", 
    "id": 256592, 
    "name": "Tur til Tyskland", 
    "pickup_place": "", 
    "pickup_time": "", 
    "place": "", 
    "starttime": "2012-01-13T01:00:00+01:00", 
    "status": "tilmeldt",
    "action_method": "PUT", 
    "action_path": "/v1/activities/256592/activities_users/2363897", 
    "actions": [],
    "coach_count": 3
}
```

**Comment by jeyben** [comment]
I would like numbers to present how many coaches are attending an activity, how many that has chosen to not attend (status=2), and if possible, how many coaches that is still in the RSVP group.

Would your count be the total number of coaches (regarding there status?)

**Comment by joerichsen** [comment]
OK, I just added a role field to each activities_user.
Role is 1 for coach and 2 for player :-)

**Comment by jeyben** [comment]
Great! I am still missing the coaches in the activities_users list though... that currently only contains players

**Comment by joerichsen** [comment]
Do you mind sharing the id of the activity where the coaches are missing?

I can take a look at it then :-)

**Comment by jeyben** [comment]
id=3465227 
the activity_users doesn't seem to contain the role attribute? is it already in production?

**Comment by joerichsen** [comment]
I changed my mind about the role thing and added activities_coaches instead :-)

It uses the same format as activities_users and it is only present on activities with the "Tilmeldte trænere tæller ikke med i deltagerantal" option checked.

The change has been deployed to production now.

**Comment by jeyben** [comment]
Thanks!
