### ISSUE TITLE
Error code 500 when trying to manipulate user status - version 2

### ISSUE THREAD

**Issue by jeyben** [Holdsport/holdsport-api#4]
I am experiencing issues manipulating data again. That return HTTP 500. My credentials are left out.

Some examples:
curl -H "Content-Type: application/json" -X POST -u “-:-“ https://api.holdsport.dk/v1/activities/3465203/activities_users -d "{"activities_user":{"picked":1,"joined_status":1,"name":"Tilmeld"}}" 

curl -H "Content-Type: application/json" -X POST -u "-:-" https://api.holdsport.dk/v1/activities/3465145/activities_users -d "{"activities_user":{"picked":1,"joined_status":1,"name":"Tilmeld"}}"

**Comment by jeyben** [comment]
Other requests that works is (manipulating the same activity):
curl -H "Content-Type: application/json" -X PUT -u "-:-" https://api.holdsport.dk/v1/activities/3465227/activities_users/22228352 -d "{"activities_user":{"picked":1,"joined_status":2,"name":"Afmeld"}}"

curl -H "Content-Type: application/json" -X PUT -u "-:-" https://api.holdsport.dk/v1/activities/3465227/activities_users/22228352 -d "{"activities_user":{"picked":1,"joined_status":1,"name":"Tilmeld"}}"

A key difference is that the two latter actions is PUT actions and the action contains the user_id in the request url

**Comment by joerichsen** [comment]
Just checked the error logs and the system is complaining about the name parameter, so leaving that out should fix the problem ie. instead of

```
curl -H "Content-Type: application/json" -X POST -u “-:-“ https://api.holdsport.dk/v1/activities/3465203/activities_users -d "{"activities_user":{"picked":1,"joined_status":1,"name":"Tilmeld"}}"
```

use

```
curl -H "Content-Type: application/json" -X POST -u “-:-“ https://api.holdsport.dk/v1/activities/3465203/activities_users -d "{"activities_user":{"picked":1,"joined_status":1}}"
```

**Comment by jeyben** [comment]
Removing the 'name' and the 'picked' attributes did the trick!

curl -H "Content-Type: application/json" -X POST -u “-:-“ https://api.holdsport.dk/v1/activities/3465203/activities_users -d '{"activities_user":{"joined_status":1}}'
