### ISSUE TITLE
Activity is sometimes in different locale (french? instead of danish)

### ISSUE THREAD

**Issue by jeyben** [Holdsport/holdsport-api#5]
When searching activities I experience the resulting activities to be in different locale than danish (my account settings I quess). This is not overtime and not often, but from time to time.

The search is performed like:
https://api.holdsport.dk/v1/teams/[teamid]/activities?date=[today]&page=1&per_page=10

In example getting an activity back containing:

```
...
    "action_method" = PUT;
    "action_path" = "/v1/activities/3465227/activities_users/22228352";
    actions =     (
                {
            "activities_user" =             {
                "joined_status" = 2;
                name = Baixa;
                picked = 1;
            };
        }
    );
...
```

instead of something like 

```
    "action_method" = PUT;
    "action_path" = "/v1/activities/3465227/activities_users/22228352";
    actions =     (
                {
            "activities_user" =             {
                "joined_status" = 2;
                name = Afmeld;
                picked = 1;
            };
        }
    );
```

**Comment by jeyben** [comment]
If this isn't easy to fix, could you then provide the event_type as an event_type_id as well?
Actually that would be nice no matter what, as the translation of the event_type would be locale independant.

**Comment by jeyben** [comment]
I have also experienced other locales like event_type: "Campeonato" which is like portuguese or spanish

**Comment by jeyben** [comment]
Could you provide the event_type_id, so I am independant of the locale?

**Comment by jeyben** [comment]
Currently I rely on the eventtypes to be in danish locale (Træning, Kampe, Stævne, Møde) which is a bad solution

**Comment by joerichsen** [comment]
Sorry for the delay :-|

I have added the event_type_id and fixed the locale problems now :-)

**Comment by jeyben** [comment]
Great and no problem! :-)
